### ISSUE TITLE
"java.lang.NoClassDefFoundError: org.apache.commons.codec.digest.DigestUtils"

### ISSUE THREAD

**Issue by aniketghagre** [mconf/mconf-mobile#4]
I am trying to run bbbAndroid i downloaded the mconf-mobile code. I went through the steps and tried to install everything as mentioned.
compilation of bbbAndroid is done properly but after selecting server when i am trying select Meeting in bbbAndroid application get crashes every time

getting following errors

"Could not find class 'org.mconf.bbb.MainRtmpConnection', referenced from method org.mconf.bbb.BigBlueButtonClient.connectBigBlueButton"

"Logger name 'org.mconf.bbb.api.Meetings' exceeds maximum length of 23 characters, using 'o_.m_.b_.a_.Meetings' instead."

"java.lang.NoClassDefFoundError: org.apache.commons.codec.digest.DigestUtils"

Could you please help me out here to solve these errors.

Please get back to me as soon as possible. Any help would be highly appreciated.

**Comment by fcecagno** [comment]
Hi aniketghagre,

Are you trying BBB-Android using the Android emulator or an Android device? Could you post here the Android version you are using?
Also you could try to search about this issue on the Internet, since it seems to be a local issue more than a project bug, see: http://stackoverflow.com/questions/9126567/method-not-found-using-digestutils-in-android

**Comment by fcecagno** [comment]
See that org.apache.commons.codec.digest.DigestUtils is loaded from the dependency commons-codec1.2.jar, so if it cannot find the method, it means that your dependencies and/or classpath are wrong.

Also, if you run "ant build-all" you will compile and download all the dependencies you may need, but after that you need to remove some compiled libraries if you want to use Eclipse (since Eclipse uses library projects as dependencies, and if you leave the compiled libraries there, it will complain about adding the same library twice). They are:

./bbb-android-core/libs/bbb-java-git.jar
./bbb-android-core/libs/flazr-git.jar

Just remove them after running "ant build-all" and you will be fine.

**Comment by fcecagno** [comment]
Hi aniketghagre,

Issues on GitHub doesn't supposed to be used like that. This is not an issue, but an information that you could find very easily if you just Google "bbb-android voice connection timeout". If you have any other doubt, please write to the mailing list (after Google about that) http://groups.google.com/group/mconf-dev.
